version: '2'
volumes:
    octoprint-data:
services:
  octoprint:
    build: ./octoprint
    restart: always
    volumes:
      - 'octoprint-data:/data'
    privileged: true
    ports:
      - "80:80"
  octodetect:
    build: ./octodetect
    restart: always
    privileged: true
    depends_on:
      - octoprint
  octoscreen:
    restart: always
    build: ./octoscreen
    privileged: true
    environment:
     - UDEV=1
    depends_on:
     - octoprint

