server:
  commands:
    serverRestartCommand: reboot
webcam:
  stream: /webcam/?action=stream
  snapshot: http://127.0.0.1:8080/?action=snapshot
  ffmpeg: /usr/bin/ffmpeg
plugins:
  DisplayLayerProgress:
    showAllPrinterMessages: false
    showHeightInStatusBar: false
    showLayerInStatusBar: false
    showOnBrowserTitle: false
    showOnNavBar: false
    showOnPrinterDisplay: false
serial:                                                                                                                                 
  autoconnect: true                                                                                                                     
  baudrate: 0                                                                                                                           
  port: AUTO
